# Generated by Django 4.1.2 on 2022-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='drivers_license',
            field=models.ImageField(upload_to='images/customerlicense_img'),
        ),
    ]
