# Generated by Django 4.1.2 on 2022-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_drivers_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='drivers_license',
            field=models.ImageField(upload_to='customerlicense_img'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='govt_issued_id',
            field=models.ImageField(upload_to='customerid_img'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(default=False, upload_to='customer_img'),
        ),
    ]
