# Generated by Django 4.1.2 on 2022-12-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_motor_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorrating',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_ratings', to='vehicle.motor'),
        ),
    ]
