# Generated by Django 4.1.2 on 2022-12-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_motor_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='BrandVehicle',
        ),
    ]
