# Generated by Django 4.1.2 on 2022-12-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='MotorImages',
        ),
    ]
