# Generated by Django 4.1.2 on 2022-12-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_rename_productimages_motorimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='pictures',
        ),
    ]
