# Generated by Django 4.1.2 on 2022-12-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_remove_motor_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotorImages',
            new_name='MotorImage',
        ),
    ]
