# Generated by Django 4.1.2 on 2022-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_rename_motorimages_motorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandvehicle',
            name='pictures',
            field=models.ImageField(default=False, upload_to='brands_img'),
        ),
        migrations.AlterField(
            model_name='motorimage',
            name='image',
            field=models.ImageField(null=True, upload_to='motors_img'),
        ),
    ]
