# Generated by Django 4.1.2 on 2023-01-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_motor_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='pictures',
            field=models.ImageField(null=True, upload_to='motors_img'),
        ),
    ]
