# Generated by Django 4.1.2 on 2022-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carowner', '0002_alter_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='drivers_license',
            field=models.ImageField(upload_to='owner_license'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.ImageField(default=False, upload_to='owner_img'),
        ),
    ]
